config/routes.rb
Rails.application.routes.draw do


  root 'categories#index'

  get "login"     => 'sessions#new'
  post "login"    => 'sessions#create'
  delete "logout" => 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get "users/admin" => 'users#admin'

  get '/users/unsubscribe/:signature' => 'users#unsubscribe', as: 'unsubscribe'

  resources :users

  resources :items

  resources :rates


  resources :categories do
    resources :items
  end

  get '/static_pages/about' => 'static_pages#about'

   get '/search' => "items#search", as: :search_items

   resources :items do
    collection do
      get 'search'
      end
    end

    require "sidekiq/web"
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
    end if Rails.env.production?
    mount Sidekiq::Web, at: "/sidekiq"

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div class="panel panel-body about">
  <div class="test well well-lg well well-lg">
    <h2>
      <i class="fa fa-quote-left fa-1x pull-left"></i>It will be everywhere and the world will have to readjust. World governments will have to readjust.<i class="fa fa-quote-right fa-1x pull-right"></i>
      <h3>
        John McAfee, Founder of McAfee
      </h3>
    </h2>
  </div>
  <div class="test well well-lg">
    <h2>
    <i class="fa fa-quote-left fa-1x pull-left"></i>Economists and journalists often get caught up in this question: Why does Bitcoin have value? And the answer is very easy. Because it is useful and scarce.<i class="fa fa-quote-right fa-1x pull-right"></i>
    <h3>
      Eric Voorhees, co-founder of Coinapult
    </h3>
    </h2>
  </div>
  <div class="test well well-lg">
    <h2 class="bevel">
    <i class="fa fa-quote-left fa-1x pull-left"></i>I do think Bitcoin is the first [encrypted money] that has the potential to do something like change the world.<i class="fa fa-quote-right fa-1x pull-right"></i>
    <h3>
      Peter Thiel, Co-Founder of Paypal
    </h3>

  </h2>
  <!-- <button type="button" class="btn btn-primary btn-lg active">Primary button</button> -->

  </div>
  <div class="col-xs-6 col-md-6 col-xs-offset-3 col-md-offset-3" id ="checkBTN">
    <%= link_to "Browse", categories_path, class:"btn btn-primary btn-lg btn-block" %>
  </div>
</div>
</div>