config/routes.rb
Rails.application.routes.draw do


  root 'categories#index'

  get "login"     => 'sessions#new'
  post "login"    => 'sessions#create'
  delete "logout" => 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get "users/admin" => 'users#admin'

  get '/users/unsubscribe/:signature' => 'users#unsubscribe', as: 'unsubscribe'

  resources :users

  resources :items

  resources :rates


  resources :categories do
    resources :items
  end

  get '/static_pages/about' => 'static_pages#about'

   get '/search' => "items#search", as: :search_items

   resources :items do
    collection do
      get 'search'
      end
    end

    require "sidekiq/web"
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
    end if Rails.env.production?
    mount Sidekiq::Web, at: "/sidekiq"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
  accepts_nested_attributes_for :items
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories=Category.all
  end

  def show
    @category = Category.find(params[:id])
    items = Item.where(:category_id => @category.id)
    @items = items.page(params[:page]).per(10)
  end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/categories/index.html.erb
<div class="panel panel-body" id="categoryPANEL">
  <% @categories.each do |category| %>

    <%# link_to category.name, category_path(category.id) %>
    <div class="well well-sm" id="categoryNAMES" style="display:none;">
      <div class="row">

          <div class="col-xs-9 col-sm-9 col-md-8 col-md-offset-1"><h1><%= category.name %></h1></div>
          <div class="col-xs-1 col-sm-2  col-md-2 col-md-offset-1" ><i class="fa fa-angle-double-right fa-4x" id="arrow"></i></div>
          <a href="/categories/<%=category.id%>"> </a>
      </div>
    </div>

  <% end %>
</div>

<script>
$(document).ready(function(){
    $('.well').each(function(){
      var catName = $(this)

      catName.slideDown(400)})

      // $('.well').each(function(){
      //     var catName = $(this)
      //     catname.click(function(){
      //         catName.animate({width:'toggle'},350);
      //     })
      //   })


});





</script>

app/views/categories/show.html.erb
<div class="panel panel-body">

    <div class="jumbotron">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-4">
          <h1 class="categoryHeading"><%= @category.name %></h1>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 quotesParent">
          <h4><div class="test" id="quotes">/</div></h4>
        </div>
      <!-- </div> -->
      <!-- <div class="row"> -->
        <div class="col-xs-4 col-sm-4 col-md-4">
        <form action="/" >
          <button type="submit", class="btn btn-info btn-large" style="display:block"><i class=" fa fa-chevron-left"></i> All Categories</button>
        </form>
      </div>
      </div>
    </div>

</div>
  <%= render '/layouts/items' %>
</div>

   <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.1/js/lightbox.js"></script>

<script>


// google.maps.event.addDomListener(window, 'load', initialize);
// google.maps.event.addDomListener(window, 'page:load', initialize);
//
// function initialize() {
//
//   console.log("map going")
//
//   console.log(lat)
//   console.log(long)
//     var myCenter = new google.maps.LatLng(lat,long);
//     var marker;
//
//     var mapProp = {
//       center: myCenter,
//       zoom:20,
//       mapTypeId:google.maps.MapTypeId.HYBRID
//     };
//     var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);

    // var marker = new google.maps.Marker({
    //   position:myCenter
    // });

    // marker.setMap(map);
    //
    // google.maps.event.addListener(marker,'click', function() {
    //   map.setZoom(16);
    //   map.setCenter(marker.getPosition());
    // });

    // var infowindow = new google.maps.InfoWindow({
    //   content: my_content
    // });
    // infowindow.open(map,marker);

  // })
// }
// google.maps.event.addDomListener(window, 'load', initialize);




// $('.ACC').each(function(){
//
//     var itemName = $(this)
//
//       itemName.click(function(e){
//
//         if ($(this).find("#hidden").is(':hidden')){
//           console.log("div hidden")
//           $(this).removeClass("hoverClOSED")
//           $(this).addClass("hoverOPEN")
//           // $(this).find("#hidden").show(300);
//           $(this).find(".social-share-button").show(400)
//           $(this).find("#hidden").css({
//               "opacity":".5",
//               "display":"block",
//           }).show(400).animate({opacity:1})
//
//           jQuery("html, body").animate({ scrollTop: $(this).offset().top - $(".navbar-collapse").height()}, 1000);
//
//
//           $(this).find("#downARROW").removeClass("fa-angle-double-down ").addClass("fa-angle-double-up")
//             e.stopPropagation();
//         }
//
//
//         else{
//           $(this).find("#hidden").css({
//               "opacity":"0",
//               "display":"block",
//           }).hide(600).animate({opacity:1})
//           $(this).removeClass("hoverOPEN")
//           $(this).find(".social-share-button").hide(100)
//           $(this).find("#downARROW").addClass("fa-angle-double-down ").removeClass("fa-angle-double-up")
//             e.stopPropagation();
//         }
//
//
//       })
//
//   })



// $(document).ready(function(){
// $("button").click(function(){
// $("div").animate({
// left: '250px',
// height: '+=150px',
// width: '+=150px'
// });
// });
// });


  // if($(this).is(':visible')) {
  //   $(this).find("#hidden").hide(400);
  // }


  // $('.well').each(function(){
  //   var itemName = $(this)
  //   if ($(this).is(":hover")){
  //     console.log("fuck")
  //   }
  // })
</script>




<%# if current_user != nil && current_user.id == item.user_id %>

  <%#= link_to 'Edit', edit_category_item_path %>
  <%#= link_to 'Delete', edit_category_item_path %>
  <%#= link_to 'Delete', item_path,
  method: :delete,
  data: { confirm: 'Are you sure?' } %>

  <%# end  %>