config/routes.rb
Rails.application.routes.draw do


  root 'categories#index'

  get "login"     => 'sessions#new'
  post "login"    => 'sessions#create'
  delete "logout" => 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get "users/admin" => 'users#admin'

  get '/users/unsubscribe/:signature' => 'users#unsubscribe', as: 'unsubscribe'

  resources :users

  resources :items

  resources :rates


  resources :categories do
    resources :items
  end

  get '/static_pages/about' => 'static_pages#about'

   get '/search' => "items#search", as: :search_items

   resources :items do
    collection do
      get 'search'
      end
    end

    require "sidekiq/web"
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
    end if Rails.env.production?
    mount Sidekiq::Web, at: "/sidekiq"

end

app/views/layouts/_item.html.erb
<%= bootstrap_form_for (@item) do |f| %>

  <%= f.text_field :name, label:'Item Name', placeholder: 'i.e. Bitcoin Minnig Rig' %>

  <%= f.text_field :city, placeholder: 'e.x Los Angeles' %>

  <%=		f.select(:state, options_for_select(us_states, "CA"))%>

  <%= f.text_field :zipcode , placeholder: '5 digit zipcode'  %>

  <%= f.file_field :image, class:'image-field' %>


  <%#= file_field_tag "images[]", type: :file, multiple: true %>

  <%= f.text_area :description,  cols: 40, rows: 4, placeholder: 'A brief description of your item'  %>

  <%= f.collection_select :category_id, Category.order(:name),:id,:name, include_blank: false %>

  <%= f.text_field :phone_number, :maxlength => 10, :size => 15, placeholder: '(555)-523-5678' %>

  <%= f.text_field :price , placeholder: 'i.e. 5.00 $', label: "Dollar Price"  %>

  <center>
    <%= f.submit "Post Item", class:"btn btn-default", id:"postITEMBTN" %>
  </center>
<% end %>

app/views/layouts/_item_show.html.erb
<div class="panel panel-body">
  <div class="well well-md hover ACC fly" id="itemNAMES">
  <div class="row">

    <div class="col-xs-4 col-sm-5 col-md-4" id="itemNAME"><h3><%= @item.name %></h3>
      <% if current_user && current_user.id  == @item.user_id || current_user && current_user.admin %>
      <div class="row">
        <div class="col-xs-5 col-sm-5 col-md-2">
        <%= link_to "Edit", edit_item_path(@item), class:"editLINk" %>
      </div>
        <%= button_to('Delete', item_path(@item), :method => 'delete', :class => 'btn btn-xs btn-warning')  %>
        <br>
      </div>
      <% end %>
    </div>
    <div class="col-xs-6 col-md-4 alignTOP"><h4>
      <!-- <i><%= @item.city %></i> -->
      <h5><i><%= @item.city%></i>, <%= @item.state %> <%= @item.zipcode %></h5>
    </h4></div>
      <% price = @item.price %>
    <div class="col-xs-5 col-md-3"><h5><%= number_to_currency(price) %></h5></div>
    <div class="col-xs-1 col-md-1">

    </div>
  </div>
  <div class="panel" >
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 content">
        <div class="row">

          <div class="col-xs-12 col-sm-12 col-md-4">
            <h6> <i class="fa fa-clock-o"></i> Added <%= time_ago_in_words(@item.created_at)%> ago</h6>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-4">
            <h5> <i class="fa fa-btc"></i> <%= (price.to_f / current_rate.to_f).round(2) %></h5>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-6">
            <h5> <i class="fa fa-phone"></i> <%= number_to_phone(@item.phone_number, area_code: true)%></h5>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12">
            <h4> <i class="fa fa-info-circle"></i> <%= @item.description %></h4>
          </div>


        <div class="locationLAT"style="display:none;">
          <%= @item.latitude %>
        </div>
        <div class="locationLON" style="display:none;">
          <%= @item.longitude %>
        </div>
        <% if @item.image_file_name %>
          <div class="item_image">
            <a class="example-image-link" href="<%=@item.image.url(:large)%>" data-lightbox="example-1"><img class="example-image" src="<%=@item.image.url(:med)%>" alt="image-1" /></a>
          </div>
        <% end %>


        <!-- </div> -->
    </div>


  </div>
  <div class="mapContainer">
    <div id="googleMap" class="map"style="width:100%; height:100%"></div>
  </div>


</div>
  <%= social_share_button_tag(@item.name, :popup => "true", :url => "http://bitlist.org/items", :popup => "true") %>

</div>


  <div class="col-xs-4 col-md-12">

</div>
</div>

app/views/layouts/_items.html.erb
<div class="panel panel-body">
  <% @items.each do |item| %>
  <div class="well well-md ACC fly" id="itemNAMES">
  <div class="row">
    <div class="col-xs-5 col-sm-5 col-md-4" id="itemNAME"><h3><%= item.name %></h3>
      <% if current_user && current_user.id  == item.user_id || current_user && current_user.admin %>
      <div class="row">
        <div class="col-xs-5 col-sm-5 col-md-2">
        <%= link_to "Edit", edit_item_path(item), class:"editLINk" %>
      </div>
          <%= button_to('Delete', item_path(item), :method => 'delete', :class => 'btn btn-xs btn-warning')  %>
      </div>
      <% end %>

    </div>
    <div class="col-xs-3 col-sm-3 col-md-4 alignTOP"><h4>
      <!-- <i><%= item.city %></i> -->
      <h5><i><%= item.city%></i>, <%= item.state %> <%= item.zipcode %></h5>
    </h4>
  </div>
      <% price = item.price %>
    <div class="col-xs-3 col-sm-2 col-md-3"><h5><%= number_to_currency(price) %></h5></div>
    <div class="col-xs-1 col-md-1 col-sm-1">
          <i class="fa fa-angle-double-down fa-4x" id="downARROW"></i>
    </div>
  </div>
  <div class="panel" style="display:none" id="hidden">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 content">
        <div class="row">

          <div class="col-xs-12 col-sm-12 col-md-4">
            <h6> <i class="fa fa-clock-o"></i> Added <%= time_ago_in_words(item.created_at)%> ago</h6>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-4">
            <h5> <i class="fa fa-btc"></i> <%= (price.to_f / current_rate.to_f).round(2) %></h5>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-6">
            <h5> <i class="fa fa-phone"></i> <%= number_to_phone(item.phone_number, area_code: true)%></h5>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12">
            <h4> <i class="fa fa-info-circle"></i> <%= item.description %></h4>
          </div>
        </div>

        <div class="locationLAT"style="display:none;">
          <%= item.latitude %>
        </div>
        <div class="locationLON" style="display:none;">
          <%= item.longitude %>
        </div>



        <!-- </div> -->
    </div>

  </div>

  <div class="mapContainer">
    <div id="googleMap" class="map"style="width:100%; height:100%"></div>
  </div>
  <% if item.image_file_name %>
  <div class="imgContainer">
    <i class="fa fa-camera"></i>
    <a class="image-link" id="image" href="<%=item.image.url(:large)%>" data-lightbox="example-1"><img class="image" src="<%=item.image.url(:med)%>" alt="image-1"></a>
    </div>
    <% end %>

</div>


  <%= social_share_button_tag(item.name, :popup => "true", :url => "bitlist.org", :popup => "true") %>



<!-- $("#item_image").find("a").html( -->
</div>
  <!-- <div id="item_image" style="display:none">

  </div> -->

  <% end %>

  <div class="col-xs-4 col-md-12">
  <%= paginate @items, :theme => 'twitter-bootstrap-3' %>
</div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="/"><i class="fa 4x fa-bitcoin b"></i>itlist</a> -->
      <div id="pay-with-btc" class="navbar-brand">
        <a href="/">
          <div id="shine"></div>
          <div id="logo">
            <div id="coin">
              <center>
                <i class="fa fa-btc logoBTC"></i>
              </center>
            </div>
            <div class="logo-text">itlist </div>
          </div>

        </a>
      </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
          <li><a href="/static_pages/about">About</a></li>
          <% if current_user && !current_user.admin %>
            <li><a href="/users/<%=current_user.id%>"><i class="fa fa-user"></i> Account </a></li>

          <% elsif !current_user %>
            <li><a data-toggle="modal" data-target="#myModal">Login</a></li>
          <% end %>

          <% if current_user && current_user.admin %>
            <li><a href="/users/admin" >Admin Pannel</a></li>
          <% end %>


      </ul>

      </form>
        <form class="navbar-form navbar-left" action="/items/new" >
          <button type="submit", class="btn btn-primary postITEMBTN"><i class="fa fa-plus"></i> Post</button>
      </form>


        <div class="nav navbar-nav navbar-left rate">

          Average rate:
          <br>
          <i class="fa fa-dollar"></i>
          <%= current_rate %>
        </div>

        <div class="nav navbar-nav navbar-right">
          <% if current_user %>
          <li> <%= link_to '<i class="fa fa-sign-out"></i> Log Out'.html_safe, logout_path, method: :delete, class: 'btn btn-hidden'%></li>
          <% end %>

        </div>

      <%= form_tag search_items_path, class:"navbar-form navbar-right", method: :get do |f| %>
      <div class="form-group">
        <%= text_field_tag :search, nil, placeholder: 'search', class:"form-control" %>
        <%= text_field_tag :location, nil, placeholder: 'near', class:"form-control" %>
      </div>
       <button type="submit" class="btn btn-default mediabtn", id:"searchBTN">
        <i class="fa fa-search"></i></button>

       <%#= submit_tag '>' %>
     <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_oauth.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <center>
        <h4 class="modal-title" id="myModalLabel">Please Login</h4>
      </center>
      </div>
      <div class="modal-body">
          <div class="row">
            
              <%= link_to '<i class="fa fa-facebook"></i> Facebook'.html_safe, "/auth/facebook", class: 'btn btn-primary btn-lg', id:'facebookBTN'%>
          </div>
          <div class="row">
              <%= link_to '<i class="fa fa-google-plus"></i> &nbsp&nbsp Google'.html_safe, "/auth/google", class: 'btn btn-danger btn-lg', id:'googleBTN'%>
          </div>
          <h5>  Bitlist will never sell your information or post to your account.</h5>
      </div>

    </div>
  </div>
</div>

app/views/layouts/_users.html.erb
<div class="panel panel-body">
  <% @users.each do |user| %>
  <div class="well well-md ACC" id="itemNAMES">
  <div class="row">
    <div class="col-xs-4 col-sm-5 col-md-4" id="itemNAME"><h3><%= user.name %></h3>

      <div class="row">
        <div class="col-xs-5 col-sm-5 col-md-2">

      </div>
          <%= button_to('Remove User', user_path(user), :method => 'delete', :class => 'btn btn-xs btn-warning')  %>
      </div>



    </div>
    <div class="col-xs-6 col-md-4 alignTOP"><h4>
      <i><%= user.items.length %></i> Items
      <h5><i><%= user.email%></i></h5>
    </h4></div>

    <div class="col-xs-5 col-md-3"><h5><%= user.uid %></h5></div>
    <div class="col-xs-1 col-md-1">
          <i class="fa fa-angle-double-down fa-4x" id="downARROW"></i>
    </div>
  </div>
  <div class="panel" style="display:none" id="hidden">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 content">
        <div class="row">

          <div class="col-xs-12 col-sm-12 col-md-4">
            <h6> <i class="fa fa-clock-o"></i> Added <%= time_ago_in_words(user.created_at)%> ago</h6>
          </div>
        </div>

        </div>




  </div>
  </div>
  <% @items = user.items
      @items = @items.page(params[:page]).per(10) %>
    <%= render '/layouts/items' %>
</div>


  <% end %>



</div>
<div class="col-xs-4 col-md-12">
<%= paginate @users, :theme => 'twitter-bootstrap-3' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">


  <!-- <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.0.0/components/reset.css">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.0.0/components/site.css"> -->
  <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.0.0/components/container.css">
  <!-- <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.0.0/components/grid.css">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.0.0/components/header.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.0.0/components/image.css">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.0.0/components/menu.css">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.0.0/components/divider.css">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.0.0/components/dropdown.css">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.0.0/components/segment.css">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.0.0/components/button.css">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.0.0/components/list.css">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.0.0/components/sidebar.css">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.0.0/components/transition.css">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.1/css/lightbox.css"> -->
  <link rel="stylesheets" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.0.0/components/message.css">

  <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link href='//fonts.googleapis.com/css?family=Ubuntu:400,400italic,700italic' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.1/css/lightbox.css">



  <title>Bitlist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
<%= render 'layouts/nav' %>
<%= render 'layouts/oauth' %>

<div class="ui container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= msg %>
        <% end %>
      <% end %>
      <%= yield %>
</div>





</body>
</html>